name = "AddLatest"
uuid = "404e4c7d-d40a-4c57-9c40-90ee175e5491"
authors = ["Dilum Aluthge"]
version = "0.1.0-DEV"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
